### ISSUE TITLE
Use example...

### ISSUE THREAD

**Issue by spiderflystudios** [inpsyde/woocommerce-product-variations-description#1]
Nowhere in your descriptions or text here...or on Wordpress.org...is there any example of what to add to one's function.php file in order to get the descriptions to display on the frontend.  All you give is the helper, but nothing that actually prints the text to the front end.  Please add an example...otherwise, the plugin really can't be used by anyone.

**Comment by catlauraherzog** [comment]
Hello!

Thanks for that hint! I'll add one to the readme soon!

Best Regards,
Thomas

**Comment by spiderflystudios** [comment]
Please do soon....we've been waiting for it.  Should have been done by now....should have been as simple as a copy/paste for someone on your team.  Would have taken just a minute to do so.

**Comment by catlauraherzog** [comment]
<a href="https://github.com/inpsyde/woocommerce-product-variations-description/blob/master/readme.txt#L35">This should</a> help.

**Comment by spiderflystudios** [comment]
This could be done a lot easier and would be update proof if it was done entirely via a plugin alone, or with a snippet you add to the functions.php page.  This example requires one to edit a template file, which will just get updated and overwritten when WooCommerce updates.  It works, but it is an inefficient means of doing so.

You should be able to just call the value of the various text areas and display it with a WooCommerce hook.

**Comment by catlauraherzog** [comment]
> This could be done a lot easier

This is open source, so why don't you contribute? :)

> You should be able to just call the value of the various text areas and display it with a WooCommerce hook.

Okay, take a look at my patch linked above. There you read:

> 1. Take a filter where you want to hook. If you want to display the descriptions before the form, use `woocommerce_before_add_to_cart_form` elsewise use `woocommerce_after_add_to_cart_form`

Where do you see that I recommend to edit a WooCommerce template file?
